services:
  transcriber:
    volumes:
      - ./data:/data

  web:
    networks:
      default:
      caddy_proxy:
        aliases:
          - student-schedule-kpi-web

networks:
  caddy_proxy:
    external: true
    name: home-services_default
